// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/application/dao/internal"
)

// internalAppInstanceDao is internal type for wrapping internal DAO implements.
type internalAppInstanceDao = *internal.AppInstanceDao

// appInstanceDao is the data access object for table app_instance.
// You can define custom methods on it to extend its functionality as you wish.
type appInstanceDao struct {
	internalAppInstanceDao
}

var (
	// AppInstance is globally public accessible object for table app_instance operations.
	AppInstance = appInstanceDao{
		internal.NewAppInstanceDao(),
	}
)

// Fill with you ideas below.
