# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:xishang:Xishang@dev66@tcp(xishang.net.cn:13307)/gfast"
        tables:          "app_instance"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/application"